stop_time = read_value('stop time', s);
get_ball_power = read_value('get ball power', s);
get_ball_time = read_value('get ball time', s);
turn_90_power = read_value('turn 90 power', s);
turn_90_time = read_value('turn 90 time', s);
turn_180_power = read_value('turn 180 power', s);
turn_180_time = read_value('turn 180 time', s);
go_back_power = read_value('go back power', s);
go_back_time = read_value('go back time', s);
veer_power_min = read_value('veer power min', s);
veer_power_max = read_value('veer power max', s);
go_forward_power = read_value('go forward power', s);
suck_power = read_value('suck power', s);
spit_power = read_value('spit power', s);
hold_power = read_value('hold power', s);
raise = read_value('servo raise', s);
lower = read_value('servo lower', s);
servo_move_time = read_value('servo move time', s);

